# Generated by Django 3.2.6 on 2021-08-29 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('function', models.SmallIntegerField(choices=[(1, 'Harvest'), (2, 'Pruning'), (3, 'Scouting'), (4, 'Other')])),
                ('created_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'field_worker',
                'verbose_name_plural': 'field_workers',
            },
        ),
    ]
