# Generated by Django 3.2.6 on 2021-08-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldworker',
            options={'verbose_name': 'fieldworker', 'verbose_name_plural': 'fieldworkers'},
        ),
        migrations.AlterField(
            model_name='fieldworker',
            name='function',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
