# Generated by Django 3.2.6 on 2021-08-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210829_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldworker',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='fieldworker',
            name='function',
            field=models.CharField(choices=[('Harvest', 'Harvest'), ('Pruning', 'Pruning'), ('Scouting', 'Scouting'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
